select * from VIEW_DUSON --where order_KG<>0

--금일포장절수, 금월포장절수
select 
	A.DAY, COUNT(B.OrderNO) As MONTH
from(
	SELECT COUNT(*) AS DAY FROM VIEW_DUSON WHERE GDATE='20240423' AND KG>0
)A
LEFT JOIN
	VIEW_DUSON B ON LEFT(GDATE,6)='202404' AND KG>0
GROUP BY A.DAY



SELECT GDATE, CUSTOMER, ORDERNO, ORder_KG, SUM(KG) As Qty, COUNT(*) As Cnt
FROM [VIEW_DUSON]
WHERE GDATE BETWEEN '20240401' AND '20240423' 
      AND KG > 0 
GROUP BY GDATE, CUSTOMER, ORDERNO,ORder_KG 
ORDER BY GDATE, CUSTOMER



select * from VIEW_DUSON where gdate='20240416' and CUSTOMER='일번텍스타일'


select * from VIEW_DUSON
SELECT
    (SELECT COUNT(*) FROM VIEW_DUSON WHERE GDATE='20240416' AND KG>0) AS Count1,
    (SELECT COUNT(*) FROM VIEW_DUSON WHERE CONVERT(char, gdate,120)-1=20240415 AND KG>0) AS Count2,
    (SELECT COUNT(*) FROM VIEW_DUSON WHERE LEFT(GDATE,6)='202404' AND KG>0) AS Count3


SELECT
(SELECT COUNT(*) FROM [VIEW_DUSON]
WHERE GDATE= '20240423'  AND KG>0) AS Count1,
(SELECT COUNT(*) FROM [VIEW_DUSON]
WHERE CONVERT(char, gdate,120) - 1= '20240422'  AND KG>0) AS Count2,
(SELECT COUNT(*) FROM [VIEW_DUSON]
WHERE LEFT(GDATE,6)= '202404'  AND KG>0) AS Count3


