SELECT A.TABLE_CATALOG, A.TABLE_NAME, ISNULL(E.Value,'') AS TABLE_REMARK,
		A.ORDINAL_POSITION, A.COLUMN_NAME, ISNULL(D.value,'') AS COLUMN_REMARK,
		CASE WHEN A.DATA_TYPE = 'char' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.CHARACTER_MAXIMUM_LENGTH) + ')'		 
			 WHEN A.DATA_TYPE = 'nchar' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.CHARACTER_MAXIMUM_LENGTH) + ')' 
		     WHEN A.DATA_TYPE = 'varchar' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.CHARACTER_MAXIMUM_LENGTH) + ')' 
			 WHEN A.DATA_TYPE = 'nvarchar' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.CHARACTER_MAXIMUM_LENGTH) + ')' 
			 WHEN A.DATA_TYPE = 'decimal' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.NUMERIC_PRECISION) + ',' + CONVERT(VARCHAR(5), A.NUMERIC_SCALE) + ')' 
			 WHEN A.DATA_TYPE = 'numeric' THEN A.DATA_TYPE + '(' + CONVERT(VARCHAR(5), A.NUMERIC_PRECISION) + ',' + CONVERT(VARCHAR(5), A.NUMERIC_SCALE) + ')' 
			 WHEN A.DATA_TYPE = 'tinyint' THEN A.DATA_TYPE 
			 WHEN A.DATA_TYPE = 'smallint' THEN A.DATA_TYPE 
			 WHEN A.DATA_TYPE = 'int' THEN A.DATA_TYPE 
			 WHEN A.DATA_TYPE = 'float' THEN A.DATA_TYPE
			 WHEN A.DATA_TYPE = 'money' THEN A.DATA_TYPE
			 WHEN A.DATA_TYPE = 'datetime' THEN A.DATA_TYPE
			 WHEN A.DATA_TYPE = 'image' THEN A.DATA_TYPE
			 WHEN A.DATA_TYPE = 'test' THEN A.DATA_TYPE
		ELSE A.DATA_TYPE END AS DATA_TYPE,
		CASE WHEN SUBSTRING(ISNULL(B.CONSTRAINT_NAME,''),1,2) = 'PK' THEN 'V' ELSE '' END AS PKEY,
		CASE WHEN SUBSTRING(ISNULL(C.CONSTRAINT_NAME,''),1,2) = 'FK' THEN 'V' ELSE '' END AS FKEY,
		CASE WHEN A.IS_NULLABLE = 'YES' THEN 'V' ELSE '' END AS NOT_NULL,
		ISNULL(A.COLUMN_DEFAULT,'') AS COLNUM_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS AS A
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS B ON A.TABLE_CATALOG = B.TABLE_CATALOG AND A.TABLE_NAME = B.TABLE_NAME AND A.COLUMN_NAME = B.COLUMN_NAME AND SUBSTRING(B.CONSTRAINT_NAME,1,2) = 'PK'
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS C ON A.TABLE_CATALOG = C.TABLE_CATALOG AND A.TABLE_NAME = C.TABLE_NAME AND A.COLUMN_NAME = C.COLUMN_NAME AND SUBSTRING(C.CONSTRAINT_NAME,1,2) = 'FK'
LEFT JOIN SYS.EXTENDED_PROPERTIES AS D ON OBJECT_ID(A.Table_Name) = D.major_id AND A.Ordinal_Position  = D.minor_id 
LEFT JOIN (SELECT  OBJECT_ID(Objname) Table_Id,Value  
           FROM    ::FN_LISTEXTENDEDPROPERTY(NULL, 'schema','dbo','Table',NULL, NULL, NULL) ) AS E ON OBJECT_ID(A.Table_Name) = E.Table_id
LEFT JOIN INFORMATION_SCHEMA.TABLES AS Z ON A.TABLE_CATALOG = z.TABLE_CATALOG AND A.TABLE_SCHEMA = Z.TABLE_SCHEMA AND A.TABLE_NAME = Z.TABLE_NAME
WHERE Z.TABLE_TYPE = 'BASE TABLE' --테이블만 조회, view 검색 필요시 조건 변경
ORDER BY A.TABLE_CATALOG, A.TABLE_NAME, A.ORDINAL_POSITION